Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	panphlan_map
	1

rule panphlan_map:
    input: /scr1/users/leej39/Sagori/sunbeam_output/qc/decontam/SRC.738313_1.fastq.gz
    output: /scr1/users/leej39/Sagori/PanPhlAn_output/map_result/SRC.738313_vparvula16.csv.bz2
    jobid: 0
    wildcards: sample=SRC.738313, clade=vparvula16


        ~/panphlan/panphlan_map.py         -c vparvula16         -i /scr1/users/leej39/Sagori/sunbeam_output/qc/decontam/SRC.738313_1.fastq.gz         --output /scr1/users/leej39/Sagori/PanPhlAn_output/map_result/SRC.738313_vparvula16.csv         --verbose
        
Error in rule panphlan_map:
    jobid: 0
    output: /scr1/users/leej39/Sagori/PanPhlAn_output/map_result/SRC.738313_vparvula16.csv.bz2

RuleException:
CalledProcessError in line 12 of /home/leej39/pan_snake/rules/map/map.rules:
Command ' set -euo pipefail;  
        ~/panphlan/panphlan_map.py         -c vparvula16         -i /scr1/users/leej39/Sagori/sunbeam_output/qc/decontam/SRC.738313_1.fastq.gz         --output /scr1/users/leej39/Sagori/PanPhlAn_output/map_result/SRC.738313_vparvula16.csv         --verbose ' returned non-zero exit status 1.
  File "/home/leej39/pan_snake/rules/map/map.rules", line 12, in __rule_panphlan_map
  File "/home/leej39/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/leej39/pan_snake/.snakemake/log/2019-08-08T120531.930473.snakemake.log
